- hosts: all
  tasks:
    - name: Создание директории для репозитория
      file:
        path: "/home/{{ ansible_user }}/MentionBot"
        state: directory

    - name: Выкачивание репозитория
      git:
        repo: "https://github.com/ddymm/MentionBot.git"
        dest: "/home/{{ ansible_user }}/MentionBot"
        single_branch: yes
        version: master

    - name: Копирование .env на удалённый сервер
      copy:
        src: ./../.env
        dest: "/home/{{ ansible_user }}/MentionBot"

    - name: Остановка контейнера
      docker_compose:
        project_src: "/home/{{ ansible_user }}/MentionBot"
        state: absent
      tags: [restart, stop]

    - name: Сборка и запуск контейнера
      docker_compose:
        project_src: "/home/{{ ansible_user }}/MentionBot"
        build: yes
      tags: [restart, start]
