- hosts: all
  tasks:
    - name: Создание директории для бота
      file:
        path: "/home/{{ ansible_user }}/MentionBot"
        state: directory
      tags: deploy

    - name: Выкачивание репозитория
      git:
        repo: "https://github.com/ddymm/MentionBot.git"
        dest: "/home/{{ ansible_user }}/MentionBot"
        single_branch: yes
        version: master
      tags: deploy

    - name: Копирование .env на удалённый сервер
      copy:
        src: ./../.env
        dest: "/home/{{ ansible_user }}/MentionBot/"
      tags: deploy

    - name: Остановка контейнера
      docker_compose:
        project_src: "/home/{{ ansible_user }}/MentionBot"
        state: absent
      tags: [deploy, restart]

    - name: Сборка и запуск контейнера
      docker_compose:
        project_src: "/home/{{ ansible_user }}/MentionBot"
        build: yes
      register: output
      tags: [deploy, restart]
